<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_AWB  618-45793705</name>
   <tag></tag>
   <elementGuidId>da5cc7a3-1408-4956-9ac7-2a61aa3c2766</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.size-14</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='resultArea']/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>bb5b487b-e258-4e8e-934f-b6b58e1ca413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>548e30dd-9b4f-4fad-99f7-4439439ac4a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>size-14</value>
      <webElementGuid>bc0b2886-1462-42b3-b3cb-e09732582002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>a0e3a03c-3ac1-43e9-b1be-822a047de192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          AWB : 618-45793705</value>
      <webElementGuid>edf63ede-6a84-46d9-8630-deba049c4daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultArea&quot;)/table[1]/tbody[1]/tr[1]/td[@class=&quot;size-14&quot;]</value>
      <webElementGuid>7ddb3b8b-98bd-4a0a-a6a5-7c09f4c8d638</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='resultArea']/table/tbody/tr/td</value>
      <webElementGuid>b961f384-d820-41d3-93e8-e32245cc07f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='* Please check entries highlighted.'])[1]/following::td[1]</value>
      <webElementGuid>ce85bd54-6249-4d4d-bab2-0bf9bb03218b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter at least 1 Air Waybill number for tracking'])[1]/following::td[1]</value>
      <webElementGuid>32fb9973-d9ec-424c-bc0e-948c8eb32c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='618-45793705']/parent::*</value>
      <webElementGuid>5428df18-58fa-49a5-b267-a8d2b094419a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td</value>
      <webElementGuid>f01855c1-e757-4749-bbf0-57e408079192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
          AWB : 618-45793705' or . = '
          AWB : 618-45793705')]</value>
      <webElementGuid>611a1135-2ee1-4c7a-8d86-03dcf28f7ff9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
