<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>VERIVY_AWB</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>50</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>8cec070e-24e3-4ce1-bc51-265153a842dc</testSuiteGuid>
   <testCaseLink>
      <guid>616604a3-45f7-416f-87c6-15eb90c584e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>1a40c9a3-d09b-4259-ba07-b0e918b2dd6a</id>
         <masked>false</masked>
         <name>awbno</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/SIA_CARGO/verifyElemetnAWB</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>92597fda-9be8-4ee8-a6f9-febfbd345cc1</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/awbData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>92597fda-9be8-4ee8-a6f9-febfbd345cc1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>awbno</value>
         <variableId>1a40c9a3-d09b-4259-ba07-b0e918b2dd6a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
