<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Air Waybill 1_Suffix1</name>
   <tag></tag>
   <elementGuidId>a551a142-c1ec-4bb6-9452-e20ce1a47ff8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Suffix1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Suffix1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>acb031cf-30ee-4a62-b21a-f0408678d444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Suffix1</value>
      <webElementGuid>cbab15a5-1b28-48ca-98d4-e0ed1c2d7379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d9a5223-c629-47a9-91e6-5ab33efa4dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Suffix1</value>
      <webElementGuid>fbdc60d2-d03a-4021-b28d-dd11e1f060e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>667c8000-f0d0-4a14-8412-4327e5649229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>MoveCursorSuffix(this)</value>
      <webElementGuid>f7a6b9c6-7071-4bd8-a5dc-6e1962475e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-suffix getInteger</value>
      <webElementGuid>13b34a8e-dee6-49f8-8a3b-8a8bf087f2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Suffix1&quot;)</value>
      <webElementGuid>de8edc18-892f-482b-a265-a65b1cdc8b9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Suffix1']</value>
      <webElementGuid>086201d1-cd33-4aaf-91c1-c58df3e3279b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='queryArea']/div[2]/div/div/div/input[2]</value>
      <webElementGuid>e97bab29-7f91-477e-8f70-0a9a98b51720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input[2]</value>
      <webElementGuid>bc2c323e-f230-489d-a64d-0edecaf77a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Suffix1' and @type = 'text' and @id = 'Suffix1']</value>
      <webElementGuid>f3df99af-0d7a-4cc1-9b8e-dc04a940c59b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
