<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Air Waybill 2_Suffix2</name>
   <tag></tag>
   <elementGuidId>89af9dbc-df95-429f-8ef9-82d61ed9e89f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Suffix2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Suffix2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec964d9e-306d-48b3-974a-83d8c4a34603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Suffix2</value>
      <webElementGuid>04b26c59-03c4-4bc0-b49d-23556999cb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bbad3a33-f860-4f71-bc83-77a332b1ae90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Suffix2</value>
      <webElementGuid>0410b72b-7a42-44e9-a994-e7c20f5f0f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>cc32bb34-0500-4397-91bd-275da4ac6172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>MoveCursorSuffix(this)</value>
      <webElementGuid>71e9004b-6c3f-486c-9eb7-2339f1ef17f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-suffix getInteger</value>
      <webElementGuid>cf469232-5d53-4141-b37e-9a5fc1e24014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Suffix2&quot;)</value>
      <webElementGuid>5e86edfe-8b0e-43db-8bb9-f54457980907</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Suffix2']</value>
      <webElementGuid>edb2ed8b-c736-4829-a616-ea60b285c08e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='queryArea']/div[2]/div/div[2]/div/input[2]</value>
      <webElementGuid>af2e5539-2d91-4d13-97f7-317955eb728e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input[2]</value>
      <webElementGuid>0a7d10fa-02ae-42c8-9a1d-78c99f1ba477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Suffix2' and @type = 'text' and @id = 'Suffix2']</value>
      <webElementGuid>5a7f02b5-3e5e-40c6-8a46-29a629fdcc8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
