<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_AWB  618-45793705</name>
   <tag></tag>
   <elementGuidId>e4d3e28f-497f-4715-aa4c-2cc28b35051b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.size-14</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='resultArea']/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b066f8d1-2042-4948-bf7d-3b79a745046b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>a099fdf7-9bd1-463a-a660-1bad373c4fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>size-14</value>
      <webElementGuid>9d351f2f-b96d-4f49-bade-db66eb383b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>9e8d1c1e-1d08-4e4c-9031-2e8af03a3116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          AWB : 618-45793705</value>
      <webElementGuid>72e08a7d-62fa-4ffd-9884-e24010631b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultArea&quot;)/table[1]/tbody[1]/tr[1]/td[@class=&quot;size-14&quot;]</value>
      <webElementGuid>4d9f7732-c20d-43df-b624-7ec6b40b0193</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='resultArea']/table/tbody/tr/td</value>
      <webElementGuid>19fb3cfa-886e-492e-9aeb-133de3e50bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='* Please check entries highlighted.'])[1]/following::td[1]</value>
      <webElementGuid>d23086f2-a32b-4655-9f48-f2a0acf62c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter at least 1 Air Waybill number for tracking'])[1]/following::td[1]</value>
      <webElementGuid>bbe045c8-18d1-4b82-9bbc-e6ff0fd74820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='618-45793705']/parent::*</value>
      <webElementGuid>d713710b-b048-4a5f-a19e-2f854215c5c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td</value>
      <webElementGuid>7ecc011d-df45-41f2-86f5-f713ab16ea61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
          AWB : 618-45793705' or . = '
          AWB : 618-45793705')]</value>
      <webElementGuid>45b66333-7856-4ce7-ae80-2cee272c3a88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
