<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Air Waybill 2_Suffix2 (1)</name>
   <tag></tag>
   <elementGuidId>67f2601d-47e6-4913-bbf8-4ea2c5506813</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Suffix2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Suffix2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f33e0c95-e515-4568-9f52-b854163258ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Suffix2</value>
      <webElementGuid>615fc0a2-84af-40ee-8689-d61894c8470c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ca985fdf-0f6c-4257-972b-131f8d04e6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Suffix2</value>
      <webElementGuid>90e327bd-b925-485f-8f45-3898865ec26a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>a2b29bac-5269-4637-b957-f16045e48138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>MoveCursorSuffix(this)</value>
      <webElementGuid>827a7ffd-2e69-4a3a-aba3-6b6be69f3b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-suffix getInteger</value>
      <webElementGuid>58fb9995-762a-4b9b-b42e-971912c83a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Suffix2&quot;)</value>
      <webElementGuid>ed168005-a50b-4be9-b266-d20335a4fa47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Suffix2']</value>
      <webElementGuid>2400f9f2-28f2-41da-bfe2-30f0ce705c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='queryArea']/div[2]/div/div[2]/div/input[2]</value>
      <webElementGuid>e004e0a9-9959-462d-932a-3473d5f2966e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input[2]</value>
      <webElementGuid>6cff8209-d46f-4ae5-8d7e-5aa725919a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Suffix2' and @type = 'text' and @id = 'Suffix2']</value>
      <webElementGuid>5c8c96d7-f595-40d0-b44f-34eec01fef40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
