<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Air Waybill 5_Suffix5</name>
   <tag></tag>
   <elementGuidId>3878860b-1fd6-4233-bd33-5da45c8afa20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Suffix5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Suffix5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4416920a-9eab-4efa-9524-028a68fd02b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Suffix5</value>
      <webElementGuid>de2564d5-2e31-4602-8229-109211bbe1d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9219904-bbc3-45c9-ab0f-1149efb59b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Suffix5</value>
      <webElementGuid>600696e6-d82d-4334-8d4f-a77e854329c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>3880b850-f7ee-44f1-a15d-9b27c2d920a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>MoveCursorSuffix(this)</value>
      <webElementGuid>6a7fb8e5-c46c-4c97-9aab-05069f354408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-suffix getInteger</value>
      <webElementGuid>3a22ab54-a7c4-4030-b2cf-ad235785084b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Suffix5&quot;)</value>
      <webElementGuid>b6f53a50-3d46-4fa1-9f89-d7f1ac5d6a5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Suffix5']</value>
      <webElementGuid>d8b0c635-eedb-4618-aaa2-1e07dae4c90d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='queryArea']/div[2]/div/div[5]/div/input[2]</value>
      <webElementGuid>b21b4a70-adc1-4e4e-a6e3-d15d48978358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input[2]</value>
      <webElementGuid>e7c21c89-be76-46c5-8b5b-7e75751a8d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Suffix5' and @type = 'text' and @id = 'Suffix5']</value>
      <webElementGuid>e063c534-2c1a-485c-a7a5-f867514faeb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
